// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udvfauinbdfyxxmbfkwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdmZhdWluYmRmeXh4bWJma3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzI1NDMsImV4cCI6MjA2ODkwODU0M30.YrjUOxh0Y3PPqpTnhvPYpBoqyq7FrUNLUN6BLxAMGQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});